"""Comprehensive SMTP presets for all major email providers."""

from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass
class SMTPPreset:
    """SMTP configuration preset for an email provider."""
    name: str              # Display name
    type: str              # Category: "china", "international", "enterprise", "custom"
    smtp_server: str
    smtp_port: int
    use_tls: bool
    security: str = ""  # ssl, starttls, or none
    imap_server: str = ""
    imap_port: int = 993
    requires_app_password: bool = True
    auth_type: str = "password"  # "password", "oauth2", "api_key"
    daily_limit: int = 500
    batch_limit: int = 50
    delay_range: tuple = (3, 10)
    notes: str = ""
    domains: List[str] = None  # Email domains this preset applies to
    requires_local_service: bool = False

    def __post_init__(self):
        if self.domains is None:
            self.domains = []
        if not self.security:
            if not self.use_tls:
                self.security = "none"
            elif self.smtp_port == 465:
                self.security = "ssl"
            else:
                self.security = "starttls"


# Comprehensive SMTP presets for all major providers
SMTP_PRESETS: Dict[str, SMTPPreset] = {
    # ============ Chinese Providers ============
    "qq": SMTPPreset(
        name="QQ邮箱",
        type="china",
        smtp_server="smtp.qq.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.qq.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=200,
        batch_limit=30,
        delay_range=(5, 15),
        domains=["qq.com", "foxmail.com"],
        notes="需开启SMTP服务并获取授权码",
    ),
    "qq_ssl": SMTPPreset(
        name="QQ邮箱 (STARTTLS 587)",
        type="china",
        smtp_server="smtp.qq.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.qq.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=200,
        batch_limit=30,
        delay_range=(5, 15),
        domains=["qq.com", "foxmail.com"],
        notes="TLS模式，某些网络环境更稳定",
    ),
    "163": SMTPPreset(
        name="163邮箱",
        type="china",
        smtp_server="smtp.163.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.163.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=50,
        delay_range=(3, 10),
        domains=["163.com"],
        notes="需开启SMTP/IMAP/POP3服务并获取授权码",
    ),
    "163_ssl": SMTPPreset(
        name="163邮箱 (STARTTLS 587)",
        type="china",
        smtp_server="smtp.163.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.163.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=50,
        delay_range=(3, 10),
        domains=["163.com"],
        notes="TLS模式",
    ),
    "126": SMTPPreset(
        name="126邮箱",
        type="china",
        smtp_server="smtp.126.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.126.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=50,
        delay_range=(3, 10),
        domains=["126.com"],
        notes="需开启SMTP/IMAP/POP3服务并获取授权码",
    ),
    "126_ssl": SMTPPreset(
        name="126邮箱 (STARTTLS 587)",
        type="china",
        smtp_server="smtp.126.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.126.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=50,
        delay_range=(3, 10),
        domains=["126.com"],
    ),
    "sina": SMTPPreset(
        name="新浪邮箱",
        type="china",
        smtp_server="smtp.sina.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.sina.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=200,
        batch_limit=30,
        delay_range=(5, 15),
        domains=["sina.com", "sina.cn"],
        notes="需开启SMTP服务",
    ),
    "sohu": SMTPPreset(
        name="搜狐邮箱",
        type="china",
        smtp_server="smtp.sohu.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.sohu.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=200,
        batch_limit=30,
        delay_range=(5, 15),
        domains=["sohu.com"],
    ),
    "yeah": SMTPPreset(
        name="Yeah.net邮箱",
        type="china",
        smtp_server="smtp.yeah.net",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.yeah.net",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=50,
        delay_range=(3, 10),
        domains=["yeah.net"],
    ),
    "aliyun_personal": SMTPPreset(
        name="阿里云个人邮箱",
        type="china",
        smtp_server="smtp.aliyun.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.aliyun.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=500,
        batch_limit=50,
        delay_range=(3, 8),
        domains=["aliyun.com"],
        notes="个人版阿里云邮箱",
    ),
    "aliyun_enterprise": SMTPPreset(
        name="阿里云企业邮箱",
        type="china",
        smtp_server="smtp.mxhichina.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.mxhichina.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=2000,
        batch_limit=100,
        delay_range=(2, 5),
        domains=[],
        notes="企业邮箱，需在控制台开启SMTP",
    ),
    "tencent_exmail": SMTPPreset(
        name="腾讯企业邮箱",
        type="china",
        smtp_server="smtp.exmail.qq.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.exmail.qq.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=2000,
        batch_limit=100,
        delay_range=(2, 5),
        domains=[],
        notes="企业微信关联邮箱，需管理员开启",
    ),
    "netease_enterprise": SMTPPreset(
        name="网易企业邮箱",
        type="china",
        smtp_server="smtp.qiye.163.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.qiye.163.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=2000,
        batch_limit=100,
        delay_range=(2, 5),
        domains=[],
    ),
    "feishu": SMTPPreset(
        name="飞书邮箱",
        type="china",
        smtp_server="smtp.feishu.cn",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.feishu.cn",
        imap_port=993,
        requires_app_password=True,
        daily_limit=1000,
        batch_limit=50,
        delay_range=(3, 8),
        domains=["lark.cn", "feishu.cn"],
        notes="需在飞书管理后台开启SMTP",
    ),
    "larksuite": SMTPPreset(
        name="Lark Mail",
        type="international",
        smtp_server="smtp.larksuite.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.larksuite.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=1000,
        batch_limit=50,
        delay_range=(3, 8),
        domains=["larksuite.com"],
        notes="需在Lark管理后台开启SMTP",
    ),
    "dingtalk": SMTPPreset(
        name="钉钉邮箱",
        type="china",
        smtp_server="smtp.qiye.aliyun.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.qiye.aliyun.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=1000,
        batch_limit=50,
        delay_range=(3, 8),
        domains=["dingtalk.com"],
    ),
    "huawei_enterprise": SMTPPreset(
        name="华为企业邮箱",
        type="china",
        smtp_server="smtp.sparkspace.huaweicloud.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.sparkspace.huaweicloud.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=2000,
        batch_limit=100,
        delay_range=(2, 5),
        domains=[],
        notes="华为云SparkSpace企业邮箱，需管理员开启SMTP",
    ),
    "wo": SMTPPreset(
        name="联通沃邮箱",
        type="china",
        smtp_server="smtp.wo.cn",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.wo.cn",
        imap_port=993,
        requires_app_password=True,
        daily_limit=200,
        batch_limit=30,
        delay_range=(5, 15),
        domains=["wo.cn"],
    ),
    "139": SMTPPreset(
        name="139邮箱",
        type="china",
        smtp_server="smtp.139.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.139.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=200,
        batch_limit=30,
        delay_range=(5, 15),
        domains=["139.com"],
    ),
    "189": SMTPPreset(
        name="189邮箱",
        type="china",
        smtp_server="smtp.189.cn",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.189.cn",
        imap_port=993,
        requires_app_password=True,
        daily_limit=200,
        batch_limit=30,
        delay_range=(5, 15),
        domains=["189.cn"],
    ),
    "naver": SMTPPreset(
        name="Naver邮箱",
        type="china",
        smtp_server="smtp.naver.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.naver.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=30,
        delay_range=(3, 10),
        domains=["naver.com"],
        notes="需开启SMTP并使用应用密码",
    ),
    "daum": SMTPPreset(
        name="Daum / Hanmail",
        type="china",
        smtp_server="smtp.daum.net",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.daum.net",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=30,
        delay_range=(3, 10),
        domains=["daum.net", "hanmail.net"],
    ),
    # ============ International Providers ============
    "gmail": SMTPPreset(
        name="Gmail",
        type="international",
        smtp_server="smtp.gmail.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.gmail.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=500,
        batch_limit=50,
        delay_range=(2, 5),
        domains=["gmail.com", "googlemail.com"],
        notes="需开启两步验证并生成应用专用密码",
    ),
    "gmail_ssl": SMTPPreset(
        name="Gmail (SSL 465)",
        type="international",
        smtp_server="smtp.gmail.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.gmail.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=500,
        batch_limit=50,
        delay_range=(2, 5),
        domains=["gmail.com", "googlemail.com"],
    ),
    "outlook": SMTPPreset(
        name="Outlook / Hotmail / Live",
        type="international",
        smtp_server="smtp-mail.outlook.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap-mail.outlook.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=30,
        delay_range=(3, 8),
        domains=["outlook.com", "hotmail.com", "live.com", "msn.com"],
        notes="需开启两步验证",
    ),
    "outlook_ssl": SMTPPreset(
        name="Outlook (SSL 465)",
        type="international",
        smtp_server="smtp-mail.outlook.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap-mail.outlook.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=30,
        delay_range=(3, 8),
        domains=["outlook.com", "hotmail.com", "live.com", "msn.com"],
    ),
    "yahoo": SMTPPreset(
        name="Yahoo Mail",
        type="international",
        smtp_server="smtp.mail.yahoo.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.mail.yahoo.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=500,
        batch_limit=50,
        delay_range=(3, 8),
        domains=["yahoo.com", "ymail.com", "rocketmail.com"],
        notes="需开启两步验证并生成应用密码",
    ),
    "yahoo_ssl": SMTPPreset(
        name="Yahoo Mail (SSL 465)",
        type="international",
        smtp_server="smtp.mail.yahoo.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.mail.yahoo.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=500,
        batch_limit=50,
        delay_range=(3, 8),
        domains=["yahoo.com", "ymail.com", "rocketmail.com"],
    ),
    "icloud": SMTPPreset(
        name="iCloud Mail",
        type="international",
        smtp_server="smtp.mail.me.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.mail.me.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=1000,
        batch_limit=50,
        delay_range=(3, 8),
        domains=["icloud.com", "me.com", "mac.com"],
        notes="需开启两步验证并生成应用专用密码",
    ),
    "aol": SMTPPreset(
        name="AOL Mail",
        type="international",
        smtp_server="smtp.aol.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.aol.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=500,
        batch_limit=50,
        delay_range=(3, 8),
        domains=["aol.com"],
    ),
    "gmx": SMTPPreset(
        name="GMX Mail",
        type="international",
        smtp_server="mail.gmx.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.gmx.com",
        imap_port=993,
        requires_app_password=False,
        daily_limit=300,
        batch_limit=30,
        delay_range=(3, 8),
        domains=["gmx.com", "gmx.net", "gmx.de"],
    ),
    "web_de": SMTPPreset(
        name="WEB.DE",
        type="international",
        smtp_server="smtp.web.de",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.web.de",
        imap_port=993,
        requires_app_password=False,
        daily_limit=300,
        batch_limit=30,
        delay_range=(3, 8),
        domains=["web.de"],
    ),
    "mail_ru": SMTPPreset(
        name="Mail.ru",
        type="international",
        smtp_server="smtp.mail.ru",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.mail.ru",
        imap_port=993,
        requires_app_password=True,
        daily_limit=500,
        batch_limit=50,
        delay_range=(3, 8),
        domains=["mail.ru", "bk.ru", "inbox.ru", "list.ru"],
    ),
    "yandex": SMTPPreset(
        name="Yandex Mail",
        type="international",
        smtp_server="smtp.yandex.com",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.yandex.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=500,
        batch_limit=50,
        delay_range=(3, 8),
        domains=["yandex.com", "yandex.ru", "ya.ru"],
    ),
    "protonmail": SMTPPreset(
        name="Proton Mail (Bridge)",
        type="international",
        smtp_server="127.0.0.1",
        smtp_port=1025,
        use_tls=False,
        imap_server="127.0.0.1",
        imap_port=1143,
        requires_app_password=False,
        daily_limit=150,
        batch_limit=20,
        delay_range=(5, 15),
        domains=["proton.me", "protonmail.com", "pm.me"],
        notes="需运行Proton Mail Bridge本地代理",
        requires_local_service=True,
    ),
    "zoho": SMTPPreset(
        name="Zoho Mail",
        type="international",
        smtp_server="smtp.zoho.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.zoho.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=50,
        delay_range=(3, 8),
        domains=["zoho.com", "zohomail.com"],
    ),
    "fastmail": SMTPPreset(
        name="Fastmail",
        type="international",
        smtp_server="smtp.fastmail.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.fastmail.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=2000,
        batch_limit=100,
        delay_range=(2, 5),
        domains=["fastmail.com", "fastmail.fm"],
    ),
    "office365": SMTPPreset(
        name="Microsoft 365",
        type="international",
        smtp_server="smtp.office365.com",
        smtp_port=587,
        use_tls=True,
        imap_server="outlook.office365.com",
        imap_port=993,
        requires_app_password=False,
        auth_type="password",
        daily_limit=10000,
        batch_limit=100,
        delay_range=(2, 6),
        domains=["office365.com"],
        notes="需管理员允许SMTP AUTH；OAuth优先",
    ),
    "mail_com": SMTPPreset(
        name="Mail.com",
        type="international",
        smtp_server="smtp.mail.com",
        smtp_port=587,
        use_tls=True,
        imap_server="imap.mail.com",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=30,
        delay_range=(3, 8),
        domains=["mail.com"],
    ),
    "t_online": SMTPPreset(
        name="T-Online",
        type="international",
        smtp_server="securesmtp.t-online.de",
        smtp_port=465,
        use_tls=True,
        imap_server="secureimap.t-online.de",
        imap_port=993,
        requires_app_password=True,
        daily_limit=300,
        batch_limit=30,
        delay_range=(3, 8),
        domains=["t-online.de"],
    ),
    "orange": SMTPPreset(
        name="Orange Mail",
        type="international",
        smtp_server="smtp.orange.fr",
        smtp_port=465,
        use_tls=True,
        imap_server="imap.orange.fr",
        imap_port=993,
        requires_app_password=False,
        daily_limit=300,
        batch_limit=30,
        delay_range=(3, 8),
        domains=["orange.fr"],
    ),
    "bluewin": SMTPPreset(
        name="Bluewin",
        type="international",
        smtp_server="smtpauths.bluewin.ch",
        smtp_port=465,
        use_tls=True,
        imap_server="imaps.bluewin.ch",
        imap_port=993,
        requires_app_password=False,
        daily_limit=300,
        batch_limit=30,
        delay_range=(3, 8),
        domains=["bluewin.ch"],
    ),
    # ============ Enterprise/API Providers ============
    "aliyun_dm": SMTPPreset(
        name="阿里云邮箱推送 (DirectMail)",
        type="enterprise",
        smtp_server="dm.aliyuncs.com",
        smtp_port=0,
        use_tls=False,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 2),
        domains=[],
        notes="API推送模式：需在阿里云控制台开通邮箱推送，配置发信域名和AccessKey",
    ),
    "aliyun_dm_25": SMTPPreset(
        name="阿里云邮箱推送 (端口25)",
        type="enterprise",
        smtp_server="smtpdm.aliyun.com",
        smtp_port=25,
        use_tls=False,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 2),
        domains=[],
    ),
    "aliyun_dm_587": SMTPPreset(
        name="阿里云邮箱推送 (端口587 TLS)",
        type="enterprise",
        smtp_server="smtpdm.aliyun.com",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 2),
        domains=[],
    ),
    "sendgrid": SMTPPreset(
        name="SendGrid",
        type="enterprise",
        smtp_server="smtp.sendgrid.net",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
        notes="用户名: apikey，密码: API Key",
    ),
    "sendgrid_ssl": SMTPPreset(
        name="SendGrid (SSL 465)",
        type="enterprise",
        smtp_server="smtp.sendgrid.net",
        smtp_port=465,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
    ),
    "mailgun": SMTPPreset(
        name="Mailgun",
        type="enterprise",
        smtp_server="smtp.mailgun.org",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
        notes="用户名: postmaster@yourdomain，密码: SMTP密码",
    ),
    "mailgun_ssl": SMTPPreset(
        name="Mailgun (SSL 465)",
        type="enterprise",
        smtp_server="smtp.mailgun.org",
        smtp_port=465,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
    ),
    "ses": SMTPPreset(
        name="Amazon SES",
        type="enterprise",
        smtp_server="email-smtp.us-east-1.amazonaws.com",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
        notes="区域不同SMTP端点不同，需生成SMTP凭证",
    ),
    "ses_eu": SMTPPreset(
        name="Amazon SES (欧盟)",
        type="enterprise",
        smtp_server="email-smtp.eu-west-1.amazonaws.com",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
    ),
    "postmark": SMTPPreset(
        name="Postmark",
        type="enterprise",
        smtp_server="smtp.postmarkapp.com",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
        notes="仅支持事务性邮件，需验证域名",
    ),
    "sparkpost": SMTPPreset(
        name="SparkPost",
        type="enterprise",
        smtp_server="smtp.sparkpostmail.com",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
    ),
    "mandrill": SMTPPreset(
        name="Mandrill (Mailchimp)",
        type="enterprise",
        smtp_server="smtp.mandrillapp.com",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
    ),
    "brevo": SMTPPreset(
        name="Brevo (Sendinblue)",
        type="enterprise",
        smtp_server="smtp-relay.brevo.com",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
    ),
    "elastic_email": SMTPPreset(
        name="Elastic Email",
        type="enterprise",
        smtp_server="smtp.elasticemail.com",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
    ),
    "mailjet": SMTPPreset(
        name="Mailjet",
        type="enterprise",
        smtp_server="in-v3.mailjet.com",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
    ),
    "pepipost": SMTPPreset(
        name="Pepipost (Netcore)",
        type="enterprise",
        smtp_server="smtp.pepipost.com",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        auth_type="api_key",
        daily_limit=100000,
        batch_limit=1000,
        delay_range=(0.5, 1),
        domains=[],
    ),
    # ============ Custom ============
    "custom": SMTPPreset(
        name="自定义SMTP",
        type="custom",
        smtp_server="",
        smtp_port=587,
        use_tls=True,
        requires_app_password=False,
        daily_limit=500,
        batch_limit=50,
        delay_range=(3, 10),
        domains=[],
        notes="手动填写服务器地址、端口、加密方式",
    ),
}


def get_preset(key: str) -> Optional[SMTPPreset]:
    """Get SMTP preset by key."""
    return SMTP_PRESETS.get(key)


def get_presets_by_type(type_filter: str) -> List[SMTPPreset]:
    """Get all presets of a specific type."""
    return [p for p in SMTP_PRESETS.values() if p.type == type_filter]


def get_preset_for_email(email: str) -> Optional[SMTPPreset]:
    """Auto-detect best preset based on email domain."""
    domain = email.split("@")[-1].lower()
    for preset in SMTP_PRESETS.values():
        if preset.domains and domain in preset.domains:
            return preset
    return None


def get_all_presets() -> Dict[str, SMTPPreset]:
    """Get all presets."""
    return SMTP_PRESETS


def get_preset_choices() -> List[dict]:
    """Get presets formatted for frontend dropdown."""
    return [
        {
            "key": key,
            "name": preset.name,
            "sender_type": (
                "自定义SMTP"
                if preset.type == "custom"
                else (
                    "阿里云邮箱推送"
                    if key == "aliyun_dm"
                    else (
                        "阿里云邮箱推送SMTP"
                        if key.startswith("aliyun_dm_")
                        else preset.name.split(" (", 1)[0]
                    )
                )
            ),
            "type": preset.type,
            "server": preset.smtp_server,
            "port": preset.smtp_port,
            "tls": preset.use_tls,
            "security": preset.security,
            "daily_limit": preset.daily_limit,
            "batch_limit": preset.batch_limit,
            "delay_range": list(preset.delay_range),
            "notes": preset.notes,
            "domains": preset.domains,
            "requires_app_password": preset.requires_app_password,
            "auth_type": preset.auth_type,
            "requires_local_service": preset.requires_local_service,
        }
        for key, preset in SMTP_PRESETS.items()
    ]
